image: nberlette/gitpod-enhanced

tasks:
  - name: Malanna
    init: pnpm install
    command: pnpm dev

ports:
  - port: 3000-5000
    onOpen: open-preview

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addBadge: true
    addCheck: true
    addLabel: true

vscode:
  extensions:
    - esbenp.prettier-vscode
