image: nberlette/gitpod-enhanced

tasks:
  - name: Malanna
    init: pnpm install
    command: pnpm run dev

ports:
  - port: 3000-5000
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - esbenp.prettier-vscode
    - editorconfig.editorconfig
    - cschleiden.vscode-github-actions
    - benjaminbenais.copilot-theme
    - eamodio.gitlens
    - jock.svg
    - mrmlnc.vscode-scss
    - heybourn.headwind
    - takumii.markdowntable
    - silvenon.mdx
    - xyc.vscode-mdx-preview
    - stefanprobst.remark-lint
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - eg2.vscode-npm-script
    - gamunu.vscode-yarn
    - bierner.markdown-preview-github-styles

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addBadge: true
    addCheck: true
    addLabel: true
